"""empty message

Revision ID: 091133163234
Revises: f7514f2718e6
Create Date: 2022-12-27 15:46:28.084091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091133163234'
down_revision = 'f7514f2718e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=550),
               existing_nullable=False)
    op.alter_column('recipes', 'image_link',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=550),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_link',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('recipes', 'description',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
