"""empty message

Revision ID: d95bda19376e
Revises: 406cceb7a2cd
Create Date: 2022-12-26 18:32:11.702109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95bda19376e'
down_revision = '406cceb7a2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_user_id_fkey', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipes_user_id_fkey', 'recipes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
