"""empty message

Revision ID: f7514f2718e6
Revises: d95bda19376e
Create Date: 2022-12-26 19:12:39.520945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7514f2718e6'
down_revision = 'd95bda19376e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_link', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_link')
    # ### end Alembic commands ###
